#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <cmath>
static uint32_t h32(uint32_t x){x^=x>>16;x*=0x7feb352dU;x^=x>>15;x*=0x846ca68bU;x^=x>>16;return x;} static float r32(uint32_t&s){s=h32(s);return(s&0xffffffu)/16777215.f;} static float hz(int n){return 440.f*std::pow(2.f,(n-69)/12.f);}
MiraForgeAudioProcessor::MiraForgeAudioProcessor():AudioProcessor(BusesProperties().withOutput("Output",juce::AudioChannelSet::stereo(),true)){synth.addSound(new Sound());for(int i=0;i<24;i++)synth.addVoice(new Voice(&params));setPresetIndex(0);}
void MiraForgeAudioProcessor::prepareToPlay(double sr,int){synth.setCurrentPlaybackSampleRate(sr);for(int i=0;i<synth.getNumVoices();i++)if(auto*v=dynamic_cast<Voice*>(synth.getVoice(i)))v->setSR(sr);}void MiraForgeAudioProcessor::releaseResources(){}
bool MiraForgeAudioProcessor::isBusesLayoutSupported(const BusesLayout&l)const{return l.getMainOutputChannelSet()==juce::AudioChannelSet::mono()||l.getMainOutputChannelSet()==juce::AudioChannelSet::stereo();}
void MiraForgeAudioProcessor::processBlock(juce::AudioBuffer<float>&b,juce::MidiBuffer&m){b.clear();synth.renderNextBlock(b,m,0,b.getNumSamples());b.applyGain(.72f);}
void MiraForgeAudioProcessor::setCurrentProgram(int i){setPresetIndex(i);}const juce::String MiraForgeAudioProcessor::getProgramName(int i){return makeName(i);}void MiraForgeAudioProcessor::setPresetIndex(int i){presetIndex=juce::jlimit(0,249999,i);applyPreset(presetIndex);}juce::String MiraForgeAudioProcessor::getPresetName()const{return makeName(presetIndex);}
MiraForgeAudioProcessor::Params MiraForgeAudioProcessor::makeParams(int i){uint32_t s=(uint32_t)i*0x9e3779b9u+0x4d495241u;Params p;p.wave=(int)(r32(s)*5);p.mix=.2f+r32(s)*.75f;p.detune=r32(s)*.22f;p.cutoff=.12f+r32(s)*.8f;p.res=r32(s)*.55f;p.attack=r32(s)*.15f;p.decay=.1f+r32(s)*1.4f;p.sustain=.35f+r32(s)*.62f;p.release=.15f+r32(s)*1.8f;p.drive=r32(s)*.4f;p.space=r32(s)*.7f;p.width=.2f+r32(s)*.8f;return p;}
juce::String MiraForgeAudioProcessor::makeName(int i){static const char*k[]={"MIDNIGHT ARP","BROKEN KEYS","DARK BELL","LOW GUITAR","HAUNTED PLUCK","CLOUD PAD","NEON RHODES","FROZEN PIANO","EMPTY ROOM","NIGHT DRIVE"};static const char*m[]={"Obsidian","Afterglow","Nocturne","Wasted","Velvet","Static","Blue Hour","Ghost","Rainfall","Eclipse"};return juce::String(k[i%10])+" • "+m[(i/10)%10]+" • "+juce::String(i+1);}
void MiraForgeAudioProcessor::applyPreset(int i){params=makeParams(i);}
void MiraForgeAudioProcessor::getStateInformation(juce::MemoryBlock&d){juce::MemoryOutputStream o(d,false);o.writeInt(presetIndex);o.writeFloat(params.mix);o.writeFloat(params.detune);o.writeFloat(params.cutoff);o.writeFloat(params.res);o.writeFloat(params.attack);o.writeFloat(params.decay);o.writeFloat(params.sustain);o.writeFloat(params.release);o.writeFloat(params.drive);o.writeFloat(params.space);o.writeFloat(params.width);o.writeInt(params.wave);}
void MiraForgeAudioProcessor::setStateInformation(const void*d,int n){if(n<4)return;juce::MemoryInputStream i(d,(size_t)n,false);presetIndex=juce::jlimit(0,249999,i.readInt());params.mix=i.readFloat();params.detune=i.readFloat();params.cutoff=i.readFloat();params.res=i.readFloat();params.attack=i.readFloat();params.decay=i.readFloat();params.sustain=i.readFloat();params.release=i.readFloat();params.drive=i.readFloat();params.space=i.readFloat();params.width=i.readFloat();params.wave=i.readInt();}
void MiraForgeAudioProcessor::Voice::startNote(int n,float v,juce::SynthesiserSound*,int){hz=MiraForgeAudioProcessor::makeParams(0).cutoff;hz=440.f*std::pow(2.f,(n-69)/12.f);vel=v;ph1=ph2=0;age=0;rel=false;}void MiraForgeAudioProcessor::Voice::stopNote(float,bool tail){rel=tail;if(!tail)clearCurrentNote();}
void MiraForgeAudioProcessor::Voice::renderNextBlock(juce::AudioBuffer<float>&b,int st,int num){if(!params)return;auto osc=[](double p,int w){double s=std::sin(juce::MathConstants<double>::twoPi*p);if(w==1)return(float)(2*(p-std::floor(p+.5)));if(w==2)return(float)(p<.5?1:-1);if(w==3)return(float)(2*std::abs(2*(p-std::floor(p+.5)))-1);if(w==4)return(float)(s*s*2-1);return(float)s;};double a=hz/sr,bb=hz*std::pow(2.,params->detune/12.)/sr;float z=0;for(int i=0;i<num;i++){float t=age/(float)sr,e;if(rel)e=std::exp(-t*4.f/juce::jmax(.08f,params->release));else if(t<params->attack)e=t/juce::jmax(.001f,params->attack);else if(t<params->attack+params->decay)e=1-(1-params->sustain)*(t-params->attack)/params->decay;else e=params->sustain;float x=(osc(ph1,params->wave)*(1-params->mix)+osc(ph2,(params->wave+1)%5)*params->mix)*e*vel;x=std::tanh(x*(1+params->drive*8));float c=.01f+params->cutoff*.25f;z+=c*(x-z);x=z;b.addSample(0,st+i,x*(1-.15f*params->width));if(b.getNumChannels()>1)b.addSample(1,st+i,x*(.85f+.15f*params->width));ph1=std::fmod(ph1+a,1.);ph2=std::fmod(ph2+bb,1.);age++;if(rel&&e<.002f){clearCurrentNote();break;}}}
juce::AudioProcessor*JUCE_CALLTYPE createPluginFilter(){return new MiraForgeAudioProcessor();}
